.env.example, package.json
=> removed PORT=3001, added my account

package.json
you need port 3001 for auth to work
=> you need port 3001 for auth to work

.history/src/common/components/FormPopup_20250226132140.jsx, .history/src/common/components/FormPopup_20250226132154.jsx, package-lock.json, src/App.css, src/App.jsx, src/common/components/navigation/NavBar.jsx, src/pages/home/Home.jsx
=> correct routing for therapist/admin

.prettierrc.js, src/common/components/navigation/NavBar.jsx
=> logo not showing up bug fixed

package-lock.json, src/common/contexts/UserContext.jsx, src/pages/therapist/TherapistSettings.jsx
=> started therapist account settings page

package-lock.json, src/common/contexts/UserContext.jsx, src/pages/admin/AdminSettings.jsx
=> Account Settings page for admin

public/index.html, src/App.css
=> global styling of colors

package-lock.json, src/common/components/PasswordChangeForm.jsx, src/pages/admin/AdminSettings.jsx
=> change password

package-lock.json, package.json, src/common/components/OrderTable.jsx
=> Paul frontend

package-lock.json, src/App.jsx, src/common/components/navigation/NavBar.jsx, src/pages/account/Login.jsx, src/pages/account/ResetPassword.jsx, src/pages/account/SignUp.jsx, src/pages/admin/AdminSettings.jsx
=> Reset Password functioning, sign up button added, login button on nav bar deleted

.prettierrc.js, package-lock.json, src/common/components/OrderTable.jsx, src/common/components/admin_modals/OrderApprovalConfirm.jsx, src/common/components/admin_modals/ReasonForDenial.jsx, src/common/components/templates/FormPopup.jsx, src/common/components/templates/YNPopup.jsx
=> chain popups for deny

package-lock.json, src/common/components/OrderTable.jsx
=> fixed item name not displaying

src/common/components/OrderTable.jsx, src/common/components/StatusDropdown.jsx, src/common/components/admin_modals/OrderDenyConfirm.jsx, src/common/components/templates/FormPopup.jsx
=> Brock frontend

src/common/components/OrderTable.jsx
=> no hardcoding url

package.json, src/App.jsx, src/pages/admin/AdminSettings.jsx
=> merge settings pages, tho incomplete imo

package.json, src/common/components/OrderTable.jsx, src/pages/admin/AdminSettings.jsx
=> added checkboxes for therapist settings

src/common/components/CancelOrderButton.jsx, src/common/components/OrderTable.jsx, src/common/components/OrderTableTherapist.jsx, src/common/components/admin_modals/NewAdmin.jsx, src/common/components/admin_modals/NewMonthlyBudget.jsx, src/pages/settings/SettingsPage.jsx
=> New Admin button / Cancel order button added

src/common/components/admin_modals/NewAdmin.jsx
=> deleted username enter from NewAdmin form

src/App.jsx, src/common/components/Text.js, src/common/components/navigation/NavBar.jsx, src/common/components/routes/ProtectedRoutes.jsx, src/common/components/routes/RoleBasedRedirect.jsx, src/pages/admin/AdminHome.jsx, src/pages/therapist/TherapistHome.jsx
=> UI changes to therapist and admin homepages, middleware to forbid access to unauthorized homepages.

src/common/components/OrderTable.jsx, src/pages/account/EmailVerification.jsx, src/pages/home/Home.jsx
=> more file migration + 'includes

src/common/components/admin_modals/NewMonthlyBudget.jsx, src/common/components/templates/FormPopup.jsx, src/pages/admin/AdminHome.jsx
=> add css styling to program budget on adminHome

src/common/components/ProgramBudgetList.jsx, src/common/components/admin_modals/NewMonthlyBudget.jsx, src/pages/admin/AdminHome.jsx, src/pages/therapist/TherapistHome.jsx
=> New Budget Grid + Minor Bug Fix

src/common/components/OrderTable.jsx, src/pages/admin/AdminHome.jsx
=> added new order button for admin

package-lock.json, src/common/components/table_pop_ups/NewOrderForm.jsx
=> add reload for neworderform

src/common/components/table_pop_ups/NewOrderForm.jsx
=> created styling for new order button

src/pages/settings/SettingsPage.jsx
=> fix adding new admin

src/common/components/OrderTable.jsx, src/common/components/utils.js
=> 3 retries for orders table admin side
